apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: mysecretpassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starterapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starterapp
  template:
    metadata:
      labels:
        app: starterapp
    spec:
      containers:
        - name: starterapp
          image: starterapp:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # exakt wie in docker-compose, nur Hostname ist der Service "postgresdb"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresdb:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_PASSWORD

          # Probes nur aktivieren, wenn du einen Health-Endpoint hast (Actuator o.Ã¤.)
          # Wenn du KEIN /actuator/health hast, lass diese Probes erstmal aus.
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: starterapp
spec:
  selector:
    app: starterapp
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
